services:
  - type: web
    name: speed-checker
    env: node
    plan: free
    branch: develop-deploy
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npx serve -s build -l 3000
    envVars:
      - key: NODE_ENV
        value: production



